// export const categoryList = [
//   {
//     id: 1,
//     value: 'place',
//     label: '🚩 Places',
//   },
//   {
//     id: 2,
//     value: 'dish',
//     label: '🍕 Dishes',
//   },
// ];

export const ratingList = [
  {
    id: 1,
    value: '1',
    label: '1🌟',
  },
  {
    id: 2,
    value: '2',
    label: '2🌟',
  },
  {
    id: 3,
    value: '3',
    label: '3🌟',
  },
  {
    id: 4,
    value: '4',
    label: '4🌟',
  },
  {
    id: 5,
    value: '5',
    label: '5🌟',
  },
];

export const dataList = [
  {
    id: 1,
    title: 'lounge resort',
    descriptivetype: 'enclosure',
    interpretation: 'settlement',
    cuisine: 'sudan',
    coverSrc: '/images/places/1_1img.jpg',
    coverSrc1:'/images/places/1_2img.jpg',
    coverSrc2:'/images/places/1_3img.jpg',
    specSrc: '/images/places/SA_Test_KordTumuli_SpectralPlotSentinelFAKE.jpg',
    gridcode: '7447',
    sitename: 'Uri',
    recordername:'Ed Burnett',
    stateregion: 'North Darfur',
    daterecord: '02/28/2023',
    descriptionimageone: 'The enclosures that make up part of the settlement of Uri are clearly visible in this image, as the angle of the sun has created strong shadows alongside walling. However, the vegetation on the bottom part of the image may make identifying enclosures here more difficult. Similar enclosures, which often indicate settlements, can be found across Darfur.',
    descriptionimagetwo: 'In this earlier image, the lower image quality and less convenient sun angle makes the enclosures harder to identify. However, the lower amount of vegetation at the bottom of the image may make enclosures in this specific location easier to identify.',
    descriptionimagethree: 'The low levels of contrast in this image may make these enclosures even harder to identify, although they are still reasonably clear.',
    sourceone:'Google Earth',
    sourcetwo:'Google Earth',
    test: 'testing Image',
    sourcethree:'Google Earth',
    dateofimageione: '15/11/2020', 
    dateofimagetwo: '01/01/2005',
    dateofimagethree: '14/10/2014', 
    adminlevel: 'North Darfur',
    seasonalconditionsprimary: 'Wet',
    seasonalconditionsalternative1: 'Dry',
    seasonalconditionsalternative2: 'Intermediate',
    seasonalconditionsalternative3: 'Dry',
    otherconditionsprimary: 'Low vegetation',
    otherconditionsalternative1: 'Low sun angle',
    otherconditionsalternative2: '',
    otherconditionsalternative3:'',
  },
  {
    id: 2,
    title: 'door urban',
    descriptivetype: 'structure',
    interpretation: 'mosque',
    cuisine: 'sudan',
    coverSrc: '/images/places/2_1img.jpg',
    coverSrc1: '/images/places/2_2img.jpg',
    coverSrc2: '/images/places/2_3img.jpg',
    specSrc: '/images/places/SA_Test_KordTumuli_SpectralPlotLandsatFAKE.jpg',
    gridcode: '8167',
    sitename: 'Gami Kurro',
    stateregion: 'North Darfur',
    recordername:'Ed Burnett',
    daterecord: '02/28/2023',
    descriptionimageone: 'In this image, high square walls can be seen around a series of regular columns (within a larger rectangular compound), oriented in the direction of Mecca, making the feature identifiable as a mosque. The high sun angle makes the walls and columns very clear, despite the low quality of the image.',
    descriptionimagetwo: 'In this image, vegetation slightly obscures the mosque, although the clear shadows from its walls and discolouration of the ground around it make it still recognisable.', 
    descriptionimagethree: 'In this image, the lower angle of the sun may make the internal columns harder to identify, as their shadows are lengthened.', sourceone:'Google Earth',
    sourcetwo:'Google Earth',
    sourcethree:'Google Earth',
    dateofprimary: '30/04/2005',
    dateofimageione: '11/20/2022',
    dateofimagetwo: '21/06/2019',
    dateofimagethree: '23/11/2020',
    test: 'testing Image',
    adminlevel: 'North Darfur',
    seasonalconditionsprimary: 'Dry',
    seasonalconditionsalternative1: 'Wet',
    seasonalconditionsalternative2: 'Intermediate',
    seasonalconditionsalternative3: 'Dry',
    otherconditionsprimary: 'High sun angle',
    otherconditionsalternative1: 'Low sun angle',
    otherconditionsalternative2: '',
    otherconditionsalternative3:'',
  },
  {
    id: 3,
    title: 'chow',
    descriptivetype: 'tumuli',
    interpretation: 'cemetery',
    cuisine: 'sudan',
    coverSrc: '/images/places/3_1img.jpg',
    coverSrc1: '/images/places/3_2img.jpg',
    coverSrc2: '/images/places/3_3img.jpg',
    specSrc: '/images/places/SA_Test_KordTumuli_SpectralPlotLandsatFAKE.jpg',
    gridcode: '12241',
    sitename: 'Uri',
    recordername:'Ed Burnett',
    stateregion: 'North Kordofan',
    daterecord: '02/28/2023',
    descriptionimageone: 'The piled rocks that make up these tumuli can be clearly identified in this image as round shapes that appear to protrude from the ground around them. Many have smaller white circles within, which may indicate that the inner part of the tumulus has collapsed.',
    descriptionimagetwo: 'In this earlier image, the tumuli are in some ways harder to identify, due to the lower quality of the image. However, the higher amount of contrast may make them easier for some surveyors to distinguish. In addition, by comparing this image to the previous image, some vegetation in the area which might be mistaken for tumuli can be distinguished (as it changes in size/shape between the images).',
    descriptionimagethree: 'The tumuli are more muted in this image, making it harder to distinguish them from the background terrain, but easier to distinguish them from the small amount of vegetation in this area.',
    sourceone:'Google Earth',
    sourcetwo:'Google Earth',
    test: 'testing Image',
    sourcethree:'Google Earth',
    dateofimageione: '28/12/2012',
    dateofimagetwo: '15/01/2005',
    dateofimagethree: '27/06/2019',
    adminlevel: 'North Darfur',
    seasonalconditionsprimary: 'Dry',
    seasonalconditionsalternative1: 'Wet',
    seasonalconditionsalternative2: 'Intermediate',
    seasonalconditionsalternative3: 'Dry',
    otherconditionsprimary: 'Low vegetation',
    otherconditionsalternative1: 'Low sun angle',
    otherconditionsalternative2: '',
    otherconditionsalternative3:'',
  },
  {
    id: 4,
    title: 'chow',
    descriptivetype: 'cairns',
    interpretation: 'burial',
    cuisine: 'tanzania',
    coverSrc: '/images/places/4_1img.jpg',
    coverSrc1: '/images/places/4_2img.jpg',
    coverSrc2: '/images/places/4_3img.jpg',
    specSrc: '/images/places/SA_Test_KordTumuli_SpectralPlotLandsatFAKE.jpg',
    gridcode: '34951',
    sitename: 'Mavumbi',
    recordername:'Akinbowale Akintayo',
    stateregion: 'Tanga',
    daterecord: '06/22/2023',
    descriptionimageone: 'Although the stone cairn has been destroyed as evident from the imagery, the signature is still clearly visible on the imagery. The presence of possible rubbles also attests to this. There are couple of other cairns located few metres away. There is a light forest with trees scattered around the cairn',
    descriptionimagetwo: 'In the alternative image, the vegetation has become denser which in turn has made the cairn difficult to see fully as it is the case in the earlier image',
    descriptionimagethree: 'The cairn is clearly not visible from this image and makes it quite difficult to identify',
    sourceone:'Google Earth',
    sourcetwo:'Google Earth',
    sourcethree:'Google Earth',
    dateofimageione: '12/03/2019',
    dateofimagetwo: '10/01/2015',
    dateofimagethree: '22/01/2002', 
    adminlevel: 'Tanga',
    test: 'testing Image',
    seasonalconditionsprimary: 'Dry',
    seasonalconditionsalternative1: 'Wet',
    seasonalconditionsalternative2: 'Intermediate',
    seasonalconditionsalternative3: 'Dry',
    otherconditionsprimary: 'Low vegetation',
    otherconditionsalternative1: 'Low sun angle',
    otherconditionsalternative2: '',
    otherconditionsalternative3:'',
  },
  {
    id: 5,
    title: 'chow',
    descriptivetype: 'structure',
    interpretation: 'settlement',
    cuisine: 'tanzania',
    coverSrc: '/images/places/5_1img.jpg',
    coverSrc1: '/images/places/5_2img.jpg',
    coverSrc2: '/images/places/5_3img.jpg',
    coverSrc3: '',
    specSrc: '/images/places/SA_Test_KordTumuli_SpectralPlotSentinelFAKE.jpg',
    gridcode: '29549',
    sitename: 'Kua ruins',
    stateregion: 'Pwani',
    daterecord: '06/28/2023',
    descriptionimageone: 'The ruins is clearly visible on the image. The outlines of the structures are still visible on the imagery. The adjoining area is heavily vegetated.',
    descriptionimagetwo: 'The image is clear enough to see the outline of the ruins although the area is still heavily forested.',
    descriptionimagethree: 'The ruins are not visibly clear as they were in the earlier image but the ruins can still be spotted. The area has also become more vegetated.',
    sourceone:'Google Earth',
    sourcetwo:'Google Earth',
    recordername:'Akinbowale Akintayo',
    sourcethree:'Google Earth',
    dateofimageione: '11/07/2013',
    dateofimagetwo: '18/06/2014',
    dateofimagethree: '22/06/2017',
    adminlevel: 'Pwani',
    test: 'testing Image',
    seasonalconditionsprimary: 'Wet',
    seasonalconditionsalternative1: 'Wet',
    seasonalconditionsalternative2: 'Wet',
    seasonalconditionsalternative3: 'Dry',
    otherconditionsprimary: '',
    otherconditionsalternative1: '',
    otherconditionsalternative2: '',
    otherconditionsalternative3:'',
  },
  {
    id: 6,
    title: 'chow',
    descriptivetype: 'surface deposit',
    interpretation: 'Notdiscernible',
    cuisine: 'botswana',
    coverSrc: '/images/places/6_1img.jpg',
    coverSrc1: '/images/places/6_2img.jpg',
    coverSrc2: '/images/places/6_3img.jpg',
    specSrc: '/images/places/SA_Test_KordTumuli_SpectralPlotPlanetFAKE.jpg',
    gridcode: '6802',
    sitename: 'Kgalagadi',
    stateregion: 'Limpu',
    daterecord: '06/28/2023',
    descriptionimageone: 'This landscape of the Kalahari Desert of Botswana exhibits a complex of salt pans which may partly be filled to shallow water depths during the rainy season. There is good evidence that they have attracted human and animal populations throughout the millenials as eveidenced by stone age artefacts found scattered around them.The water pans are usually dry and they dont retain water over long period of time as seen in this image.',
    descriptionimagetwo: 'There are some dark marks on some pans in this historic image, which could be associated with wet mud residue left behind when the water evaporate from the water pans. Despite that, no significant change is noticed when comparing to recent images.  ',
    descriptionimagethree: 'Thewater pans continues to shrink in size and numbers as less rainfall is recorded and some are covered by the sand which have potential of burying the artefacts around them. ', 
    sourceone:'Google Earth',
    sourcetwo:'Google Earth',
    sourcethree:'Google Earth',
    dateofimageione: '01/12/2020',
    dateofimagetwo: '31/12/1984',
    recordername:'Thabo Kgosietsile',
    dateofimagethree: '31/12/1991',
    seasonalconditionsprimary: 'Dry',
    test: 'testing Image',
    seasonalconditionsalternative1: 'Dry',
    seasonalconditionsalternative2: 'Dry',
    seasonalconditionsalternative3: 'Dry',
    otherconditionsprimary: 'No vegetation',
    otherconditionsalternative1: 'No vegetation',
    otherconditionsalternative2: 'No vegetation',
    otherconditionsalternative3:'',
  },
  {
    id: 7,
    title: 'chow',
    descriptivetype: 'structure',
    interpretation: 'settlement',
    cuisine: 'zimbabwe',
    coverSrc: '/images/places/7_1img.jpg',
    coverSrc1: '/images/places/7_2img.jpg',
    coverSrc2: '/images/places/7_3img.jpg',
    specSrc: '/images/places/SA_Test_KordTumuli_SpectralPlotPlanetFAKE.jpg',
    gridcode: '4832',
    sitename: 'none',
    stateregion: 'manicaland',
    daterecord: '07/30/2021',
    descriptionimageone: 'A large pit structure with associated terracing as well as adjacent smaller pit structures. These structures are typical of early settlements associated with the Nyanga culture and are found in high concentrations in elevated areas. Due to the high annual summer rainfall in the region, combined with excessive dry winters, the best time of the year to search for these sites are late winter or early spring when the area is at it driest with most of the deciduous plant grow still being dormant.  ',
    descriptionimagetwo: 'During mid winter the crass of the region is still largely green from the summer rains, which has a noticeable impact on how the site features look on imagery. ',
    descriptionimagethree: 'Image quality has a significant impact on how site appear, as can be seen in this images taken 3 years and 7 days after the previous one. ', 
    sourceone:'Google Earth',
    sourcetwo:'Google Earth',
    sourcethree:'Google Earth',
    dateofimageione: '14/09/2011',
    dateofimagetwo: '02/05/2014',
    recordername:'Renier van der Merwe',
    dateofimagethree: '12/05/2017',
    seasonalconditionsprimary: 'Dry',
    test: 'testing Image',
    seasonalconditionsalternative1: 'Wet',
    seasonalconditionsalternative2: 'wet',
    seasonalconditionsalternative3: '',
    otherconditionsprimary: 'burned',
    otherconditionsalternative1: 'Grass covered',
    otherconditionsalternative2: 'Grass covered',
    otherconditionsalternative3:'',
  },
  {
    id: 8,
    title: 'chow',
    descriptivetype: 'structure',
    interpretation: 'fort',
    cuisine: 'zimbabwe',
    coverSrc: '/images/places/8_1img.jpg',
    coverSrc1: '/images/places/8_2img.jpg',
    coverSrc2: '/images/places/8_3img.jpg',
    specSrc: '/images/places/SA_Test_KordTumuli_SpectralPlotPlanetFAKE.jpg',
    gridcode: '4832',
    sitename: 'chawomera fort',
    stateregion: 'manicaland',
    daterecord: '07/30/2021',
    descriptionimageone: 'A structure associated with the Nyanga culture whose function is unknown. These structures consist of either one large circular/rectangular wall or with a secondary wall located within the outer wall. Due to the thickness and the generally shallow deposits, it is believed that these structured were used as temporary defensive position, which it why they are known as Nyanga forts. Due to the high annual summer rainfall in the region, combined with excessive dry winters, the best time of the year to search for these sites are late winter or early spring when the area is at it driest with most of the deciduous plant grow still being dormant. ',
    descriptionimagetwo: 'An example of the second variation of Nyanga fortifications that is known of. In the image the second walling can be seen within the outer walling.',
    descriptionimagethree: 'Not available ', 
    sourceone:'Google Earth',
    sourcetwo:'Google Earth',
    sourcethree:'Google Earth',
    dateofimageione: '07/08/2006',
    dateofimagetwo: '14/09/2011',
    recordername:'Renier van der Merwe',
    dateofimagethree: '07/2022',
    seasonalconditionsprimary: 'Dry',
    seasonalconditionsalternative1: 'Wet',
    seasonalconditionsalternative2: 'wet',
    test: 'testing Image',
    seasonalconditionsalternative3: '',
    otherconditionsprimary: 'low vegetation',
    otherconditionsalternative1: 'Spars vegetation',
    otherconditionsalternative2: '',
    otherconditionsalternative3:'',
  },
  {
    id: 9,
    title: 'chow',
    descriptivetype: 'pond',
    interpretation: 'agiculture',
    cuisine: 'tanzania',
    coverSrc: '/images/places/9_1img.jpg',
    coverSrc1: '/images/places/9_2img.jpg',
    coverSrc2: '/images/places/9_3img.jpg',
    specSrc: '/images/places/SA_Test_KordTumuli_SpectralPlotPlanetFAKE.jpg',
    gridcode: '87499',
    sitename: 'Mchito',
    stateregion: 'Dodoma',
    daterecord: '06/28/2023',
    descriptionimageone: 'The watering hole can be visibly seen on the imagery which in turn makes it easy to identify. There is presence of surface algae on the water',
    descriptionimagetwo: ' The watering hole is still visible on the image and the surrounding environment did not change significantly. However, there are no algae on the water surface ',
    descriptionimagethree: 'The watering hole is still visible on the image and the surrounding environment has not changed significantly. However, the diameter of the pond has increased with more algae around it.', 
    sourceone:'Google Earth',
    sourcetwo:'Google Earth',
    sourcethree:'Google Earth',
    dateofimageione: '2002/09/10',
    dateofimagetwo: '2011/07/27',
    recordername:'Akinbowale Akintayo',
    dateofimagethree: '2007/5/23',
    seasonalconditionsprimary: 'Intermediate',
    test: 'testing Image',
    seasonalconditionsalternative1: 'Intermediate',
    seasonalconditionsalternative2: 'Wet',
    seasonalconditionsalternative3: 'Dry',
    otherconditionsprimary: 'Clear',
    otherconditionsalternative1: '',
    otherconditionsalternative2: '',
    otherconditionsalternative3:'',
  },
  {
    id: 10,
    title: 'chow',
    descriptivetype: 'rockshelter',
    interpretation: 'habitation',
    cuisine: 'tanzania',
    coverSrc: '/images/places/10_1img.jpg',
    coverSrc1: '/images/places/10_2img.jpg',
    coverSrc2: '/images/places/10_3img.jpg',
    specSrc: '/images/places/SA_Test_KordTumuli_SpectralPlotPlanetFAKE.jpg',
    gridcode: '84835',
    sitename: 'Apis',
    stateregion: 'Arusha',
    daterecord: '11/16/2003',
    descriptionimageone: 'The massive rock is part of a rock formation although it stands alone. The surrounding plain area makes it conspicuous within the environment where it is situated.',
    descriptionimagetwo: ' The big rock casts a shadow to the north which is attributable to the angle of sun inclination when the image was taken.',
    descriptionimagethree: 'There is a new road few metres away from the rock.', 
    sourceone:'Google Earth',
    sourcetwo:'Google Earth',
    sourcethree:'Google Earth',
    dateofimageione: '2013/7/11',
    dateofimagetwo: '2005/01/16',
    recordername:'Akinbowale Akintayo',
    dateofimagethree: '2013/08/22',
    seasonalconditionsprimary: 'Dry',
    test: 'testing Image',
    seasonalconditionsalternative1: 'Intermediate',
    seasonalconditionsalternative2: 'Dry',
    seasonalconditionsalternative3: 'Dry',
    otherconditionsprimary: 'Clear',
    otherconditionsalternative1: '',
    otherconditionsalternative2: '',
    otherconditionsalternative3:'',
  },
  {
    id: 11,
    title: 'chow',
    descriptivetype: 'grass',
    interpretation: 'settlement',
    cuisine: 'botswana',
    coverSrc: '/images/places/11_1img.jpg',
    coverSrc1: '/images/places/11_2img.jpg',
    coverSrc2: '/images/places/11_3img.jpg',
    specSrc: '/images/places/SA_Test_KordTumuli_SpectralPlotPlanetFAKE.jpg',
    gridcode: '11355',
    sitename: 'Khubu la dintsa',
    stateregion: 'Central District',
    daterecord: '06/26/2023',
    descriptionimageone: 'Dense stands of cenchrus ciliaris (buffalo grass) is noticed growing on hilltop locations across the country. These locations appear as white spots on Google Earth or aerial photographs because they are covered with grass rather than bushes or trees, and  it has proved useful in pinpointing the locations of archaeological sites as cenchrus ciliaris was found to be associated with prehistoric middens and animal kraals or recently abandoned kraals. The midden or kraal location is visible in this image, as the lush green sometimes with dark hues strongly stands out from the surrounding vegetation during the rainy or summer season.  ',
    descriptionimagetwo: ' The outlines of the prehistoric midden or kraal indicated on this image captured during the winter season are less sharper than those shown in the primary image. The bare patches visible during the dry season makes it difficult to distinguish between potential stands of cenchrus cilliaris and bare rock outcrops, however,  a denser vegetation cover is found to be most reliable.',
    descriptionimagethree: 'There is a new road few metres away from the rock.', 
    sourceone:'Google Earth',
    sourcetwo:'Google Earth',
    sourcethree:'Google Earth',
    dateofimageione: '2015/1/9',
    dateofimagetwo: '2020/08/09',
    recordername:'Thabo Kgosietsile',
    dateofimagethree: '2008/12/14',
    seasonalconditionsprimary: 'Wet',
    test: 'testing Image',
    seasonalconditionsalternative1: 'Dry',
    seasonalconditionsalternative2: 'Wet',
    seasonalconditionsalternative3: '',
    otherconditionsprimary: 'High vegetation',
    otherconditionsalternative1: 'Low vegetation',
    otherconditionsalternative2: 'Poor resolution ',
    otherconditionsalternative3:'',
  },
  {
    id: 12,
    title: 'chow',
    descriptivetype: 'surface deposit',
    interpretation: 'settlement',
    cuisine: 'botswana',
    coverSrc: '/images/places/12_1img.jpg',
    coverSrc1: '/images/places/12_2img.jpg',
    coverSrc2: '/images/places/12_3img.jpg',
    specSrc: '/images/places/SA_Test_KordTumuli_SpectralPlotPlanetFAKE.jpg',
    gridcode: '3673',
    sitename: 'Site 8, 9',
    stateregion: 'Central District',
    daterecord: '02/26/2023',
    descriptionimageone: 'The ashy grey-coloured soil visible in this image are usually midden or dung deposit sites, the accumulations of dung on these sites were once mistaken for middens, owing to the presence of bone and ceramics in an ashy matrix, but now it is apparent that they are also the remains of livestock kraals. The visibilty is great when there is less vegetation cover more especially during the dry season as evidenced in this image.',
    descriptionimagetwo: ' In this image, grass cover is dense because of the wet season and though the soil discoloration is still visible, it is not prominent as in the primary image. ',
    descriptionimagethree: 'Here, transition from wet to dry season (summer to winter) happening in the month of May in the southern hemisphere helps in making the dung deposit or midden visible, however it is still obscure and not prominent as in the primary image. ', 
    sourceone:'Google Earth',
    sourcetwo:'Google Earth',
    sourcethree:'Google Earth',
    dateofimageione: '2012/08/29',
    dateofimagetwo: '2016/02/03',
    recordername:'Thabo Kgosietsile',
    dateofimagethree: '2006/5/20',
    seasonalconditionsprimary: 'Dry',
    test: 'testing Image',
    seasonalconditionsalternative1: 'Wet',
    seasonalconditionsalternative2: 'Wet',
    seasonalconditionsalternative3: 'Intermediate',
    otherconditionsprimary: 'Low vegetation',
    otherconditionsalternative1: 'Dense grass cover',
    otherconditionsalternative2: 'Poor resolution ',
    otherconditionsalternative3:'Low vegetation',
  },
  {
    id: 13,
    title: 'chow',
    descriptivetype: 'enclosure',
    interpretation: 'settlement',
    cuisine: 'zimbabwe',
    coverSrc: '/images/places/13_1img.jpg',
    coverSrc1: '/images/places/13_2img.jpg',
    coverSrc2: '/images/places/13_3img.jpg',
    specSrc: '/images/places/SA_Test_KordTumuli_SpectralPlotPlanetFAKE.jpg',
    gridcode: '6733',
    sitename: 'none',
    stateregion: 'Manicaland',
    daterecord: '08/31/2021',
    descriptionimageone: 'One of the two most common type of settlements associated with the Nyanga culture, the pit enclosure is marked by a large circular walling surrounded by terracing and other enclosures. Historically, the central area would have a lower pit, but these are most often not seen. The pit was surrounded by a raised, walled platform on which the houses were build. Generally having a circular shape, it can be an irregular circular as well. Due to the high annual summer rainfall in the region, combined with excessive dry winters, the best time of the year to search for these sites are late winter or early spring when the area is at it driest with most of the deciduous plant grow still being dormant. ',
    descriptionimagetwo: ' Another example of the more circular version in which the central pit can be seen.',
    descriptionimagethree: 'Another example of an pit enclosure with the large form of terracing or pathed walk ways that typically links it with other enclosures. ', 
    sourceone:'Google Earth',
    sourcetwo:'Google Earth',
    sourcethree:'Google Earth',
    dateofimageione: '9/14/2011',
    dateofimagetwo: '9/14/2011',
    recordername:'Renier van der Merwe',
    dateofimagethree: '9/14/2011',
    seasonalconditionsprimary: 'Dry',
    test: 'testing Image',
    seasonalconditionsalternative1: 'Dry',
    seasonalconditionsalternative2: 'Dry',
    seasonalconditionsalternative3: 'Intermediate',
    otherconditionsprimary: 'Spars vegetation',
    otherconditionsalternative1: 'Spars vegetation',
    otherconditionsalternative2: 'Spars vegetation ',
    otherconditionsalternative3:'',
  },
  {
    id: 14,
    title: 'chow',
    descriptivetype: 'enclosure',
    interpretation: 'settlement',
    cuisine: 'zimbabwe',
    coverSrc: '/images/places/14_1img.jpg',
    coverSrc1: '/images/places/14_2img.jpg',
    coverSrc2: '/images/places/14_3img.jpg',
    specSrc: '/images/places/SA_Test_KordTumuli_SpectralPlotPlanetFAKE.jpg',
    gridcode: '6733',
    sitename: 'none',
    stateregion: 'Manicaland',
    daterecord: '09/14/2011',
    descriptionimageone: 'Another type of pit enclosure that is associated with the Nyanga culture, this settlement type is identified by the by two circular enclosures, with on constructed higher than the other and generally separated by a terrace.Due to the high annual summer rainfall in the region, combined with excessive dry winters, the best time of the year to search for these sites are late winter or early spring when the area is at it driest with most of the deciduous plant grow still being dormant. ',
    descriptionimagetwo: '',
    descriptionimagethree: 'Pit enclosures are very difficult to find with in wooded areas. Fortuantly, they are primarly found in regions with decidious tree and thus the bets time to look for them is in winter months. ', 
    sourceone:'Google Earth',
    sourcetwo:'Google Earth',
    sourcethree:'Bing',
    dateofimageione: '9/14/2011',
    dateofimagetwo: '9/16/2015',
    recordername:'Renier van der Merwe',
    dateofimagethree: '2023',
    seasonalconditionsprimary: 'Dry',
    test: 'testing Image',
    seasonalconditionsalternative1: 'Dry',
    seasonalconditionsalternative2: 'Dry',
    seasonalconditionsalternative3: 'Intermediate',
    otherconditionsprimary: 'Spars vegetation',
    otherconditionsalternative1: 'Spars vegetation',
    otherconditionsalternative2: 'With covering vegetation ',
    otherconditionsalternative3:'',
  },
  {
    id: 15,
    title: 'chow',
    descriptivetype: 'terracing',
    interpretation: 'terracing',
    cuisine: 'zimbabwe',
    coverSrc: '/images/places/14_1img.jpg',
    coverSrc1: '/images/places/14_2img.jpg',
    coverSrc2: '/images/places/14_3img.jpg',
    specSrc: '/images/places/SA_Test_KordTumuli_SpectralPlotPlanetFAKE.jpg',
    gridcode: '6733',
    sitename: 'none',
    stateregion: 'Manicaland',
    daterecord: '09/14/2011',
    descriptionimageone: 'Terracing is found extensively throughout the region, which is generally considered to be one of the most extensively terraced regions in Africa. Although a common feature, these terracing do look slightly different in different regions.Due to the high annual summer rainfall in the region, combined with excessive dry winters, the best time of the year to search for these sites are late winter or early spring when the area is at it driest with most of the deciduous plant grow still being dormant. ',
    descriptionimagetwo: 'Example of terracing found in the grassland at higher elevations in the mountains.',
    descriptionimagethree: ' ', 
    sourceone:'Google Earth',
    sourcetwo:'Google Earth',
    sourcethree:'Bing',
    dateofimageione: '9/14/2011',
    dateofimagetwo: '9/16/2015',
    recordername:'Renier van der Merwe',
    dateofimagethree: '2023',
    seasonalconditionsprimary: 'Dry',
    test: 'testing Image',
    seasonalconditionsalternative1: 'Wet',
    seasonalconditionsalternative2: 'Dry',
    seasonalconditionsalternative3: 'Intermediate',
    otherconditionsprimary: 'Spars vegetation',
    otherconditionsalternative1: 'Grass covered',
    otherconditionsalternative2: 'With covering vegetation ',
    otherconditionsalternative3:'',
  },
  {
    id: 16,
    title: 'chow',
    descriptivetype: 'cairn',
    interpretation: 'burial',
    cuisine: 'kenya',
    coverSrc: '/images/places/16_1img.jpg',
    coverSrc1: '/images/places/16_2img.jpg',
    coverSrc2: '/images/places/16_2img.jpg',
    specSrc: '/images/places/SA_Test_KordTumuli_SpectralPlotPlanetFAKE.jpg',
    gridcode: '61311',
    sitename: 'none',
    stateregion: 'Marsabit',
    daterecord: '07/07/2023',
    descriptionimageone: 'The ring cairn is visibly evident by the circular shape with a dot inside it. The area in which this is found has plenty of similar ring cairns which points toward the area being a burial site.',
    descriptionimagetwo: 'There isnt much difference in this alternative image since the area is a semi-arid dry area. Vegetation changes hardly occur therefore the site looks similarr to the primary image.',
    descriptionimagethree: ' ', 
    sourceone:'Google Earth',
    sourcetwo:'Google Earth',
    sourcethree:'Bing',
    dateofimageione: '2021/1/19',
    dateofimagetwo: '2012/03/19',
    recordername:'Pamela Ochungo',
    dateofimagethree: '2023',
    seasonalconditionsprimary: 'Dry',
    test: 'testing Image',
    seasonalconditionsalternative1: 'Dry',
    seasonalconditionsalternative2: 'Dry',
    seasonalconditionsalternative3: 'Dry',
    otherconditionsprimary: 'Mainly scrub and scattered woodland.',
    otherconditionsalternative1: 'Mainly scrub and scattered woodland.',
    otherconditionsalternative2: 'Mainly scrub and scattered woodland. ',
    otherconditionsalternative3:'',
  },
  {
    id: 17,
    title: 'chow',
    descriptivetype: 'enclosure',
    interpretation: 'agiculture',
    cuisine: 'kenya',
    coverSrc: '/images/places/17_1img.jpg',
    coverSrc1: '/images/places/17_2img.jpg',
    coverSrc2: '/images/places/17_2img.jpg',
    specSrc: '/images/places/SA_Test_KordTumuli_SpectralPlotPlanetFAKE.jpg',
    gridcode: '61311',
    sitename: 'none',
    stateregion: 'Marsabit',
    daterecord: '07/07/2023',
    descriptionimageone: 'The general shape of the individual enclosures is seen in this image in northern Kenya.',
    descriptionimagetwo: 'The enclosures are much more visible in this earlier image of the erea. This implies that there may have been destruction of the enclosures in the recent times.',
    descriptionimagethree: ' ', 
    sourceone:'Google Earth',
    sourcetwo:'Google Earth',
    sourcethree:'Bing',
    dateofimageione: '2021/1/19',
    dateofimagetwo: '2012/03/20',
    recordername:'Pamela Ochungo',
    dateofimagethree: '2012/03/20',
    seasonalconditionsprimary: 'Dry',
    test: 'testing Image',
    seasonalconditionsalternative1: 'Dry',
    seasonalconditionsalternative2: 'Dry',
    seasonalconditionsalternative3: 'Dry',
    otherconditionsprimary: 'Very scatterd bushes.',
    otherconditionsalternative1: 'Scattered bushes',
    otherconditionsalternative2: 'Scattered bushes. ',
    otherconditionsalternative3:'',
  },
  {
    id: 18,
    title: 'chow',
    descriptivetype: 'cairn',
    interpretation: 'burial',
    cuisine: 'kenya',
    coverSrc: '/images/places/18_1img.jpg',
    coverSrc1: '/images/places/18_2img.jpg',
    coverSrc2: '/images/places/18_2img.jpg',
    specSrc: '/images/places/SA_Test_KordTumuli_SpectralPlotPlanetFAKE.jpg',
    gridcode: '58885',
    sitename: 'none',
    stateregion: 'Marsabit',
    daterecord: '07/07/2023',
    descriptionimageone: 'This is a square cairn found in Northern Kenya. Its still not very clear why the cairn is square as opposed to circular that the majority of cairns on the area consist of.',
    descriptionimagetwo: 'The image seen here shows the cairn more isibly. Probably the season is drier and therefore less interference from vegetation.',
    descriptionimagethree: ' ', 
    sourceone:'Google Earth',
    sourcetwo:'Google Earth',
    sourcethree:'Bing',
    dateofimageione: '2021/1/19',
    dateofimagetwo: '2010/05/08',
    recordername:'Pamela Ochungo',
    dateofimagethree: '2010/05/08',
    seasonalconditionsprimary: 'Seems to be wet season in that particular area',
    test: 'testing Image',
    seasonalconditionsalternative1: 'Dry',
    seasonalconditionsalternative2: 'Dry',
    seasonalconditionsalternative3: 'Dry',
    otherconditionsprimary: 'Has a more bush and treecover than other areas in the region..',
    otherconditionsalternative1: 'Scattered bushes and treecover',
    otherconditionsalternative2: 'Scattered bushes and treecover. ',
    otherconditionsalternative3:'',
  },
  {
    id: 19,
    title: 'chow',
    descriptivetype: 'tumuli',
    interpretation: 'cemetery',
    cuisine: 'senegal',
    coverSrc: '/images/places/19_1img.jpg',
    coverSrc1: '/images/places/19_2img.jpg',
    coverSrc2: '/images/places/19_3img.jpg',
    specSrc: '/images/places/SA_Test_KordTumuli_SpectralPlotPlanetFAKE.jpg',
    gridcode: 'W15.875N14.625',
    sitename: 'Thieken Mbacké',
    stateregion: 'Bassin arcachidier ',
    daterecord: '06/22/2023',
    descriptionimageone: 'Structures circulaires bien en évidence et devant représentées des des affleurements de tumulus funéraires.',
    descriptionimagetwo: 'Image de la saison des pluies et la couverture herbacée permet de reconnaitre clairement les contoures des structures.',
    descriptionimagethree: 'image prise pendant la saison séche, la couverture végétale est absente. Les buttes sont bien en évidence du fait de l affleurement de sable sur les parties supérieures des buttes  ', 
    sourceone:'Google Earth',
    sourcetwo:'Google Earth',
    sourcethree:'Google Earth',
    dateofimageione: '8/7/2022',
    dateofimagetwo: '2015/11/08',
    recordername:'Nicolas',
    dateofimagethree: '8/6/2016',
    seasonalconditionsprimary: 'Seems to be wet season in that particular area',
    test: 'testing Image',
    seasonalconditionsalternative1: 'Dry',
    seasonalconditionsalternative2: 'Wet',
    seasonalconditionsalternative3: 'Dry',
    otherconditionsprimary: 'Collapsed',
    otherconditionsalternative1: 'Low vegetation',
    otherconditionsalternative2: 'Halos circulaire et cratère respectivement sur les parties basses et hautes des buttes.',
    otherconditionsalternative3:'',
  },
  {
    id: 20,
    title: 'chow',
    descriptivetype: 'soil',
    interpretation: 'cattle pen',
    cuisine: 'zimbabwe',
    coverSrc: '/images/places/20_1img.jpg',
    coverSrc1: '/images/places/20_2img.jpg',
    coverSrc2: '/images/places/20_2img.jpg',
    specSrc: '/images/places/SA_Test_KordTumuli_SpectralPlotPlanetFAKE.jpg',
    gridcode: 'E29.625S22.125',
    sitename: 'Tshobwane ',
    stateregion: 'Matabeleland ',
    daterecord: '08/17/2023',
    descriptionimageone: 'Cattle pen archaeological (or dung deposits) sites appear as circular cleared or whitish-colored patches within the savannah woody vegetation. Remains of animal byres in the form of dung deposits are some of the major characteristic features of settlements of early settlers across the Shashi-Limpopo confluence area. The visibilty of sites is better in low vegetation areas, especially during the dry season (between June and August) as evidenced in this image.',
    descriptionimagetwo: 'In this image, the soil discoloration is less visible as vegetation cover becomes denser in the wet season.',
    descriptionimagethree: ' ', 
    sourceone:'Google Earth',
    sourcetwo:'Google Earth',
    sourcethree:'Google Earth',
    dateofimageione: '2015/7/13',
    dateofimagetwo: '2010/07/20',
    recordername:'Serge Kiala ',
    dateofimagethree: '2010/07/20',
    seasonalconditionsprimary: 'Dry',
    test: 'testing Image',
    seasonalconditionsalternative1: 'Wet',
    seasonalconditionsalternative2: 'Wet',
    seasonalconditionsalternative3: '',
    otherconditionsprimary: 'Low vegetation',
    otherconditionsalternative1: 'Dense vegetation cover',
    otherconditionsalternative2: 'Dense vegetation cover',
    otherconditionsalternative3:'',
  },
  {
    id: 21,
    title: 'chow',
    descriptivetype: 'structure',
    interpretation: 'cattle pen',
    cuisine: 'zimbabwe',
    coverSrc: '/images/places/21_1img.jpg',
    coverSrc1: '/images/places/21_2img.jpg',
    coverSrc2: '/images/places/21_2img.jpg',
    specSrc: '/images/places/SA_Test_KordTumuli_SpectralPlotPlanetFAKE.jpg',
    gridcode: 'E29.625S22.125',
    sitename: ' ',
    stateregion: 'Matabeleland ',
    daterecord: '06/26/2023',
    descriptionimageone: 'Modern cattle pen sites are close to settlements in the Sashi-Limpopo confluence area and are characterised by dark soil.  Their shape is mostly rectangular, although some of them may appear circular.',
    descriptionimagetwo: 'As seen in this image, some modern cattle pen sites in the past may no longer exists today. It is worthnoting that seasonal changes do not affect the visibility of sites.',
    descriptionimagethree: ' ', 
    sourceone:'Google Earth',
    sourcetwo:'Google Earth',
    sourcethree:'Google Earth',
    dateofimageione: '2012/08/29',
    dateofimagetwo: '2013/09/20',
    recordername:'Serge Kiala ',
    dateofimagethree: '2013/09/20',
    seasonalconditionsprimary: 'Wet',
    test: 'testing Image',
    seasonalconditionsalternative1: 'Dry',
    seasonalconditionsalternative2: 'Dry',
    seasonalconditionsalternative3: '',
    otherconditionsprimary: 'High vegetation',
    otherconditionsalternative1: 'Low vegetation ',
    otherconditionsalternative2: 'Low vegetation ',
    otherconditionsalternative3:'',
  },
  {
    id: 22,
    title: 'chow',
    descriptivetype: 'cairns',
    interpretation: 'burial',
    cuisine: 'kenya',
    coverSrc: '/images/places/22_1img.jpg',
    coverSrc1: '/images/places/22_2img.jpg',
    coverSrc2: '/images/places/22_3img.jpg',
    specSrc: '/images/places/SA_Test_KordTumuli_SpectralPlotPlanetFAKE.jpg',
    gridcode: '128',
    sitename: 'Kalacha ',
    stateregion: 'Marsabit ',
    daterecord: '06/30/2023',
    descriptionimageone: 'Ring cairns visible as dark circles with dark spots in the middle. They may be hard to identify due to sorrounding rocky terrain. Usually found around living settlements.',
    descriptionimagetwo: '',
    descriptionimagethree: 'Cairns clearly visisble', 
    sourceone:'Google Earth',
    sourcetwo:'Google Earth',
    sourcethree:'Google Earth',
    dateofimageione: '2009/5/26',
    dateofimagetwo: '2013/07/05',
    recordername:'A Kabiru ',
    dateofimagethree: '2012/06/05',
    seasonalconditionsprimary: 'Dry',
    test: 'testing Image',
    seasonalconditionsalternative1: 'Intermediate',
    seasonalconditionsalternative2: 'Dry',
    seasonalconditionsalternative3: '',
    otherconditionsprimary: 'Cloudy',
    otherconditionsalternative1: 'Cloudy ',
    otherconditionsalternative2: 'Low vegetation ',
    otherconditionsalternative3:'',
  },
  {
    id: 23,
    title: 'chow',
    descriptivetype: 'mound',
    interpretation: 'settelement',
    cuisine: 'mali',
    coverSrc: '/images/places/23_1img.jpg',
    coverSrc1: '/images/places/23_2img.jpg',
    coverSrc2: '/images/places/23_2img.jpg',
    specSrc: '/images/places/SA_Test_KordTumuli_SpectralPlotPlanetFAKE.jpg',
    gridcode: '2079',
    sitename: ' ',
    stateregion: 'Mopti ',
    daterecord: '10/10/2022',
    descriptionimageone: 'Surface of earth (tell) that stands out from the surrounding environment. Ovoid in shape like this one, the mounds can be circular or even take on an irregular shape. Several mounds can also be connected. On the image, erosion can be seen (lines running from the center of the mound outwards). An occupation mound may or may not be surrounded by vegetation, as in this case.',
    descriptionimagetwo: 'Compared to the previous image, the vegetation is much darker. ',
    descriptionimagethree: '', 
    sourceone:'Google Earth',
    sourcetwo:'Google Earth',
    sourcethree:'Google Earth',
    dateofimageione: '2013/12/25',
    dateofimagetwo: '2011/11/27',
    recordername:'Eloise Noc ',
    dateofimagethree: '2011/11/27',
    seasonalconditionsprimary: 'Wet',
    test: 'testing Image',
    seasonalconditionsalternative1: 'Dry',
    seasonalconditionsalternative2: '',
    seasonalconditionsalternative3: '',
    otherconditionsprimary: '',
    otherconditionsalternative1: ' ',
    otherconditionsalternative2: ' ',
    otherconditionsalternative3:'',
  },
  {
    id: 24,
    title: 'chow',
    descriptivetype: 'mound',
    interpretation: 'settelement',
    cuisine: 'mali',
    coverSrc: '/images/places/24_1img.jpg',
    coverSrc1: '/images/places/24_2img.jpg',
    coverSrc2: '/images/places/24_2img.jpg',
    specSrc: '/images/places/SA_Test_KordTumuli_SpectralPlotPlanetFAKE.jpg',
    gridcode: '2103',
    sitename: ' ',
    stateregion: 'Mopti ',
    daterecord: '10/10/2022',
    descriptionimageone: 'Surface of earth (tell) that stands out from the surrounding environment. Ovoid in shape like this one, the mounds can be circular or even take on an irregular shape. Here, it seems that 2 mounds are connected. On the image, erosion can be seen (lines running from the center of the mound outwards) in the two different part of the site. An occupation mound may or may not be surrounded by vegetation, as in this case.',
    descriptionimagetwo: 'Compared to the previous image, the vegetation is much darker. ',
    descriptionimagethree: '', 
    sourceone:'Google Earth',
    sourcetwo:'Google Earth',
    sourcethree:'Google Earth',
    dateofimageione: '2021/03/08',
    dateofimagetwo: '2014/03/04',
    recordername:'Eloise Noc ',
    dateofimagethree: '2011/11/27',
    seasonalconditionsprimary: 'Dry',
    test: 'testing Image',
    seasonalconditionsalternative1: 'Dry',
    seasonalconditionsalternative2: '',
    seasonalconditionsalternative3: '',
    otherconditionsprimary: '',
    otherconditionsalternative1: ' ',
    otherconditionsalternative2: ' ',
    otherconditionsalternative3:'',
  },
  // {
  //   id: 7,
  //   title: 'chow',
  //   descriptivetype: 'structure',
  //   interpretation: 'settlement',
  //   cuisine: 'zimbabwe',
  //   coverSrc: '/images/places/7_1img.jpg',
  //   coverSrc1: '/images/places/7_2img.jpg',
  //   coverSrc2: '/images/places/7_3img.jpg',
  //   specSrc: '/images/places/SA_Test_KordTumuli_SpectralPlotPlanetFAKE.jpg',
  //   gridcode: '4832',
  //   sitename: 'none',
  //   stateregion: 'Manicaland',
  //   daterecord: '17/08/2023',
  //   descriptionimageone: 'This landscape of the Kalahari Desert of Botswana exhibits a complex of salt pans which may partly be filled to shallow water depths during the rainy season. There is good evidence that they have attracted human and animal populations throughout the millenials as eveidenced by stone age artefacts found scattered around them.The water pans are usually dry and they dont retain water over long period of time as seen in this image.',
  //   descriptionimagetwo: 'There are some dark marks on some pans in this historic image, which could be associated with wet mud residue left behind when the water evaporate from the water pans. Despite that, no significant change is noticed when comparing to recent images.  ',
  //   descriptionimagethree: 'Thewater pans continues to shrink in size and numbers as less rainfall is recorded and some are covered by the sand which have potential of burying the artefacts around them. ', 
  //   sourceone:'Google Earth',
  //   sourcetwo:'Google Earth',
  //   sourcethree:'Google Earth',
  //   dateofimageione: '28/06/2023',
  //   dateofimagetwo: '31/12/1984',
  //   recordername:'Thabo',
  //   dateofimagethree: '31/12/1991',
  //   seasonalconditionsprimary: 'Dry',
  //   seasonalconditionsalternative1: 'Dry',
  //   seasonalconditionsalternative2: 'Dry',
  //   seasonalconditionsalternative3: 'Dry',
  //   otherconditionsprimary: 'No vegetation',
  //   otherconditionsalternative1: 'No vegetation',
  //   otherconditionsalternative2: 'No vegetation',
  //   otherconditionsalternative3:'',
  // }
  // {
  //   id: 8,
  //   title: 'chow',
  //   descriptivetype: 'fort',
  //   interpretation: 'structure',
  //   cuisine: 'zimbabwe',
  //   coverSrc: '/images/places/8_1img.jpg',
  //   coverSrc1: '/images/places/8_2img.jpg',
  //   coverSrc2: '/images/places/8_3img.jpg',
  //   specSrc: '/images/places/SA_Test_KordTumuli_SpectralPlotPlanetFAKE.jpg',
  //   gridcode: '4832',
  //   sitename: 'Chawomera',
  //   stateregion: 'Manicaland',
  //   daterecord: '30/07/2021',
  //   descriptionimageone: 'A structure associated with the Nyanga culture whose function is unknown. These structures consist of either one large circular/rectangular wall or with a secondary wall located within the outer wall. Due to the thickness and the generally shallow deposits, it is believed that these structured were used as temporary defensive position, which it why they are known as Nyanga forts. Due to the high annual summer rainfall in the region, combined with excessive dry winters, the best time of the year to search for these sites are late winter or early spring when the area is at it driest with most of the deciduous plant grow still being dormant. ',
  //   descriptionimagetwo: 'An example of the second variation of Nyanga fortifications that is known of. In the image the second walling can be seen within the outer walling.',
  //   descriptionimagethree: 'The low levels of contrast in this image may make these enclosures even harder to identify, although they are still reasonably clear.',
  //   sourceone:'Google Earth',
  //   sourcetwo:'Google Earth',
  //   sourcethree:'Google Earth',
  //   dateofimageione: '07/08/2006',
  //   dateofimagetwo: '14/09/2011',
  //   dateofimagethree: '28/07/2022',
  //   adminlevel: 'North Kordofan',
  //   seasonalconditionsprimary: 'Dry',
  //   recordername:'Ed Burnett',
  //   seasonalconditionsalternative1: 'Dry',
  //   seasonalconditionsalternative2: 'Dry',
  //   seasonalconditionsalternative3: 'Dry',
  //   otherconditionsprimary: 'Low vegetation',
  //   otherconditionsalternative1: 'Spars vegetation',
  //   otherconditionsalternative2: '',
  //   otherconditionsalternative3:'',
  // },
  
  //   id: 11,
  //   title: 'chow',
  //   descriptivetype: 'cairns',
  //   interpretation: 'tumuli',
  //   cuisine: 'botswana',
  //   coverSrc: '/images/places/SA_Test_KordTumuli_3.jpg',
  //   specSrc: '/images/places/SA_Test_KordTumuli_SpectralPlotLandsatFAKE.jpg',
  //   gridcode: '7447',
  //   sitename: 'Uri',
  //   stateregion: 'North Darfur',
  //   daterecord: '05/01/2023',
  //   descriptionimageone: 'The enclosures that make up part of the settlement of Uri are clearly visible in this image, as the angle of the sun has created strong shadows alongside walling. However, the vegetation on the bottom part of the image may make identifying enclosures here more difficult. Similar enclosures, which often indicate settlements, can be found across Darfur.',
  //   descriptionimagetwo: 'In this earlier image, the lower image quality and less convenient sun angle makes the enclosures harder to identify. However, the lower amount of vegetation at the bottom of the image may make enclosures in this specific location easier to identify.',
  //   descriptionimagethree: 'The low levels of contrast in this image may make these enclosures even harder to identify, although they are still reasonably clear.',
  //   sourceone:'Google Earth',
  //   sourcetwo:'Google Earth',
  //   sourcethree:'Google Earth',
  //   dateofimageione: '13/06/2023',
  //   dateofimagetwo: '30/04/2005',
  //   dateofimagethree: '28/12/2012',
  //   adminlevel: 'North Darfun',
  //   seasonalconditionsprimary: 'Dry',
  //   seasonalconditionsalternative1: 'Wet',
  //   seasonalconditionsalternative2: 'Intermediate',
  //   seasonalconditionsalternative3: 'Dry',
  //   recordername:'Ed Burnett',
  //   otherconditionsprimary: 'Low vegetation',
  //   otherconditionsalternative1: 'Low sun angle',
  //   otherconditionsalternative2: '',
  //   otherconditionsalternative3:'',
  // },
  // {
  //   id: 12,
  //   title: 'chow',
  //   descriptivetype: 'cairns',
  //   interpretation: 'tumuli',
  //   cuisine: 'botswana',
  //   coverSrc: '/images/places/SA_Test_KordTumuli_3.jpg',
  //   specSrc: '/images/places/SA_Test_KordTumuli_SpectralPlotSentinelFAKE.jpg',
  //   gridcode: '7447',
  //   sitename: 'Gami Kurro',
  //   stateregion: 'North Kordofan',
  //   recordername:'Ed Burnett',
  //   daterecord: '04/22/2023',
  //   descriptionimageone: 'The enclosures that make up part of the settlement of Uri are clearly visible in this image, as the angle of the sun has created strong shadows alongside walling. However, the vegetation on the bottom part of the image may make identifying enclosures here more difficult. Similar enclosures, which often indicate settlements, can be found across Darfur.',
  //   descriptionimagetwo: 'In this earlier image, the lower image quality and less convenient sun angle makes the enclosures harder to identify. However, the lower amount of vegetation at the bottom of the image may make enclosures in this specific location easier to identify.',
  //   descriptionimagethree: 'The low levels of contrast in this image may make these enclosures even harder to identify, although they are still reasonably clear.',
  //   sourceone:'Google Earth',
  //   sourcetwo:'Google Earth',
  //   sourcethree:'Google Earth',
  //   dateofimageione: '15/06/2023',
  //   dateofimagetwo: '30/04/2005',
  //   dateofimagethree: '28/12/2012',
  //   adminlevel: 'North Kordofan',
  //   seasonalconditionsprimary: 'Dry',
  //   seasonalconditionsalternative1: 'Wet',
  //   seasonalconditionsalternative2: 'Intermediate',
  //   seasonalconditionsalternative3: 'Dry',
  //   otherconditionsprimary: 'Low vegetation',
  //   otherconditionsalternative1: 'Low sun angle',
  //   otherconditionsalternative2: '',
  //   otherconditionsalternative3:'',
  // },
  // {
  //   id: 4,
  //   title: 'wharf seafood',
  //   serviceTime: '10-18min',
  //   deliveryFee: 2.14,
  //   category: 'place',
  //   cuisine: 'american',
  //   rating: 1,
  //   price: 1800,
  //   coverSrc: '/images/places/sea.jpg',
  // },
  // {
  //   id: 5,
  //   title: 'Tossin',
  //   serviceTime: '25-30min',
  //   deliveryFee: 6.79,
  //   category: 'place',
  //   cuisine: 'italian',
  //   rating: 5,
  //   price: 2000,
  //   coverSrc: '/images/places/italiian.jpg',
  // },
  // {
  //   id: 6,
  //   title: 'stories noodles',
  //   serviceTime: '5-15min',
  //   deliveryFee: 2.87,
  //   category: 'place',
  //   cuisine: 'chinese',
  //   rating: 5,
  //   price: 3500,
  //   coverSrc: '/images/places/fookyew2.jpg',
  // },
  // {
  //   id: 7,
  //   title: 'Nacho cheeseburger',
  //   serviceTime: '50-65min',
  //   deliveryFee: 8.5,
  //   category: 'dish',
  //   cuisine: 'american',
  //   rating: 2,
  //   price: 2200,
  //   coverSrc: '/images/dishes/nacho-burger.jpg',
  // },
  // {
  //   id: 8,
  //   title: 'Mushroom Risotto',
  //   serviceTime: '10-15min',
  //   deliveryFee: 1.8,
  //   category: 'dish',
  //   cuisine: 'italian',
  //   rating: 1,
  //   price: 1900,
  //   coverSrc: '/images/dishes/Mushroom-Risotto-Recipe-1-1200.jpg',
  // },
  // {
  //   id: 9,
  //   title: 'Shitake Fried Rice',
  //   serviceTime: '12-18min',
  //   deliveryFee: 3.33,
  //   category: 'dish',
  //   cuisine: 'chinese',
  //   rating: 4,
  //   price: 2750,
  //   coverSrc: '/images/dishes/shiitake-salmon-fried-rice-0218-103230720.jpg',
  // },
  // {
  //   id: 10,
  //   title: 'Pesto chicken stew',
  //   serviceTime: '30-38min',
  //   deliveryFee: 1.9,
  //   category: 'dish',
  //   cuisine: 'american',
  //   rating: 2,
  //   price: 4350,
  //   coverSrc: '/images/dishes/pesto-chicken.jpg',
  // },
  // {
  //   id: 11,
  //   title: 'Bruschetta',
  //   serviceTime: '16-20min',
  //   deliveryFee: 4.1,
  //   category: 'dish',
  //   cuisine: 'italian',
  //   rating: 3,
  //   price: 3300,
  //   coverSrc: '/images/dishes/as-tomato-bruschetta-articleLarge.jpg',
  // },
  // {
  //   id: 12,
  //   title: 'Dim Sums',
  //   serviceTime: '24-30min',
  //   deliveryFee: 1.5,
  //   category: 'dish',
  //   cuisine: 'chinese',
  //   rating: 2,
  //   price: 4100,
  //   coverSrc: '/images/dishes/dimsums.jpg',
  // },
];
